/**
 * Generated by scripts/generate-images.mjs — do not edit by hand.
 *
 * Run `npm run images` after adding a master to assets/source.
 */

/**
 * Inline 24px previews, one per photograph. They hold the frame on the first
 * paint so nothing reflows when the real file arrives, and cost no request.
 */
export const BLUR: Record<string, string> = {
  'partners/nib-and-nosh-card': 'data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAADQBQCdASoYAB4APt1gpEyopiOiMBgMARAbiUAWdB32DMDo4NVz3F660qpLKSY8lmY44xzA+RMAAP7qldMi86OBwrOF7zM2xDzazGPJuvlyv9I7gs7GXoZ6xKbwlQVtP9yg4/w2GFzvLrjhMGXQFZPrtHYv8a/EcCKqgqLw/zqyzvQothiMdyjlxXF8D2Wt6eu5GQdXCcaCI6/FlvJL4s+PuT4kgTxQvV7/60vDWNGfqmYm4drv5Bs0jSXJt+x5oYXMGIUxqe3eAOGWuoVkkdwlUv11t/Hnd+InAAAA',
  'partners/nib-and-nosh-interior-1': 'data:image/webp;base64,UklGRiIBAABXRUJQVlA4IBYBAAAwBgCdASoYAB4APt1eqE4opSOiMBgIARAbiWYAnSDmanG3SrqYe2AvylJqlTINvYkBXj1hWlxYy3yAAP7rRwj0Nk6yiIHQloUtDzdKgBiSsILKorPii1RnczWREApSbf3mR7FnvXsUY3o/eg+PiHG1O9lNg/losfDLf2GkZptBph9gMvzRHzitzF89P402TGvgq4m0/USnivs5l1ccVOayUFmBJbEBZYIpwxxwDW035V6sIz1RkAvcq/Nqq623CA/0D3M9tW1e6Dbx6XnxCrc+I0WbXVr5E+jiuPeHNEwNd3hfk6UPDuheJyIb3Cen8/LkB2Ypgjl7JUTClO2+Vq+9LFse/cvOJOhdf/LSFOroIu44sqAAAA==',
  'partners/nib-and-nosh-interior-2': 'data:image/webp;base64,UklGRmQBAABXRUJQVlA4IFgBAAAQBwCdASoYAB4APt1cqU6opKOiMBgIARAbiWwArB2J6wDSAbgAc8VheKP/4DbQWzMcTFv1JPkuCw8qZ3z3FHD8AAD+3r6yqflV92Yr2FC0sqnms9aC2N7NV6lCPL05SYuNGw/RalOL9HVt/nNVubJGFON43H23w95cTAy2XNs0E4bGBsmOIfk154BxRIb1HNvTxwLL1aFJAn1Md13savSJx0XFUVQ/NIX1tNgMWVJV1NTysuGz6KH0/7bYbGf5shTNR7t60wf4kwgNJTz2Qc/RLvVABe7glkszqhdquthCzWnz5PoqKVh4ufCZipXM2QhSnMLUgWrybIp+9V3p5dGGA/tbEgnV6N/wuU9SVQqqto7IObStuLTniFbQw567dud/sOqWdW1VpDSJGIoOdtwqWbiLoPJhydGFhdKQyUvu7PPqHjgpbZiodudV8A955z+O68a/djqAAA==',
  'partners/nib-and-nosh-frame-1': 'data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADQBACdASoYAB4APr1So0ynJSOiN+gA4BeJYwAAiZrNDMOoIBZ5hICX5jPbvUT3AAD+7UagJWHhF1tvfXTn3Lnp7ynUhnOUeTjkqewCH7/z3tv5UP8AU0OpwJfWfFy/XBrSIQou7GZDTqMts1uS4rrfeAv9IhN9r8EJRY60LQKeeCLzP1PZQlD8lsGqFPxZOBWgaMJ5dJjhLxMqla6xK3JhtkQ59xJc4xIsjSfHgAAAAA==',
  'partners/nib-and-nosh-frame-2': 'data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAADQBACdASoYAB4APt1sqVAopiOiqAqpEBuJZACdMsdFMDwhJkRMYK+lMeAhKPNmgAD+7ToO+Iu5JziUD0gSZ/7MVffhQMgY9qLwPY6MEgc0HKAMCv3kqGb3/sEP0htzV5n87hehDk98SxzwgDa5L1tZqHfY1TJv7sO3bmryDx5+GsyrbjpZtqMssQZN4ewzMr+R3mRkoqWYuYqiDuDv6bS3AAA=',
  'partners/nib-and-nosh-frame-3': 'data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAABQBQCdASoYAB4APt1ao02opSMiMBgMARAbiWIAuwAQvJDzt1x8HEOEaQQsNMUoUx606AAA/oxOt+evS5c055Z42/iCJlbWjXX5zPe5LjqfH47j5jMp20DmYHXMrS5qYcA7d99BCkHiP2MR6DUhytX0t39DGnR4b+eM4ce49EK71XmVnj8yPKoUh3cvzI7yr16ubojLb3/EChxvkCfJ/dNu1Q+6qAAA',
  'partners/nib-and-nosh-frame-4': 'data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAAAwBQCdASoYAB4APt1iqE+opSOiKAqpEBuJbACxBuAALCcrr1xSJYans/HNbDfwL2sQAAD+3+gm6B+EurAw3FX6ASA0W6VPkjSgYe+A+ppYTXjE93bHBYsM3RJFO7gYtANocqZ2vWXUtZQPyo+UpeSbRhtV5hX+dQwKbamYjh7jsRc3zsyOsp0PRXHEDGTglV/jwzwF8G6KSMlf5eaYIzNAognDN8fytc52EH/LKPBd2h015Sj1vkFywKeyDn9acCkZ1BgA',
  'partners/nib-and-nosh-frame-5': 'data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAAAQBQCdASoYAB4APtVapUyoJaOiMAwBABqJYwDO7CHfGj7xrK/+MUVSqOswgD2hhNgAAP7rJ2UvxoeVHCxKEFE64uJnp6WmT1qC637VzAUk+Wml95P5SVitquSyThMC/QEaI+LGORziynYT+ueBHzXXmfef3DlDhEZEWc3bVKmnXHLrBbeBlO5VdeVqtlt7yH9u24rPlqfDgWlhnyw/NxC9Hn7tK7PKDqzhGeDhH3+LKUjf4+Ktw7nm/Mm5bO2R5MrjeKGmudoYk8AA',
  'partners/nib-and-nosh-frame-6': 'data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAADwBQCdASoYAB4APt1YpE2opKMiMBgMARAbiWMArAHcC4aSHeI+1HxfCmPFx4u9IejUNZnKMNNwAAD+8Getv9hBUcBqkSUrgI00ZRPZPbeMfDi+fTl4EStBolGLQXf5MB777uP/PX2qVWUjQArFTm41/EQQ7T4PlZQ3+8FhdBAztqATDIQjD0II0kT2XrJ/GsQtqvmrRt/JVROqwmlUWloqEcCGSVUx2qYcTzKhMwdYlsEH7z0X9cV0/8IxGdneC/4zzeBjvJ6EsayBGRYyCQLjNOHKtcM0VhMgAA==',
  'testimonials/oummishra': 'data:image/webp;base64,UklGRvQAAABXRUJQVlA4IOgAAAAQBgCdASoYACAAPt1YpE2opKMiMBgMARAbiWMArDMhpckk/X0EOE8FrkziE4luoVB6DLCsTzyNpIAA/uqA19SJLR2Rm77R0YFFHfkd0oeui+VVUJfEZPg20aoz6SJX5WSz0HcVVhTSl0zDJlobvsIVWHpzy9ifVTBEjb+YSRse9MzdSVBC9VtkcwnTvNmsSk4ux7jHMFJfJXmwwNaKHWCuqEX8Zb8cZeJf3WDFKKIqwRGzvqL8cqHePqoxyPuAB8ug8w4pJM6qLEegZoyLiAmlgWirOBX1wHT3TehmeX1Qeco78FWtAAAA',
  'testimonials/sachin': 'data:image/webp;base64,UklGRuoAAABXRUJQVlA4IN4AAACQBQCdASoYACAAPt1gqE4opaOiMBgIARAbiWIAnTM5Zc0JztTg2rM4luRTM3NQaa3MbXU5AAD8iQueFYeOP30291R9EsynbVBfpRmQ29EdJMFyMWd6KZ7lDP5eFbQDdzSmhEO9fC623Z8QDq5lb6CHVe3tkXX0QU+oz19BRCBNvlbP62IzXFRrRdseu/KlVtK72sppgbrHjqFqnCX/fJ30LiP1V6d+rlprKUIQlRZRiHPHPz0JUZ87Bhc1fU6UuNhUvetalKIWzU8xj9sIm8ElexNa4t86ex3hhD5OgAA=',
};

/** Which widths actually exist on disk, so a srcSet never points at a 404. */
export const WIDTHS: Record<string, number[]> = {
  'partners/nib-and-nosh-card': [480, 768, 1024],
  'partners/nib-and-nosh-interior-1': [480, 768, 1024],
  'partners/nib-and-nosh-interior-2': [480, 768, 1024],
  'partners/nib-and-nosh-frame-1': [480, 768, 1024],
  'partners/nib-and-nosh-frame-2': [480, 768, 1024],
  'partners/nib-and-nosh-frame-3': [480, 768, 1024],
  'partners/nib-and-nosh-frame-4': [480, 768, 1024],
  'partners/nib-and-nosh-frame-5': [480, 768, 1024],
  'partners/nib-and-nosh-frame-6': [480, 768, 1024],
  'testimonials/oummishra': [360, 720],
  'testimonials/sachin': [360, 720],
};

/**
 * The base name for a generated file, or null if this URL is not one of ours.
 *
 * "/image/partners/nib-and-nosh-1024.webp" → "partners/nib-and-nosh"
 */
export function generatedNameFor(url: string): string | null {
  const match = /^\/image\/(.+?)-\d+\.webp$/.exec(url);
  if (match && WIDTHS[match[1]]) return match[1];

  // Also accept the bare name, so a caller can address the photograph without
  // committing to one of its widths.
  const bare = url.replace(/^\/image\//, '').replace(/\.webp$/, '');
  return WIDTHS[bare] ? bare : null;
}
