import { passwordSchema } from '@artinu/shared';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation } from '@tanstack/react-query';
import { KeyRound } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { z } from 'zod';
import { AuthCard, AuthSplit } from '@/components/layout/AuthLayout';
import { Button } from '@/components/ui/button';
import { Field } from '@/components/ui/field';
import { PasswordInput } from '@/components/ui/input';
import { PasswordRules } from '@/features/auth/components/AuthBits';
import { useAuth } from '@/contexts/AuthContext';
import { errorMessage } from '@/lib/api';
import { IMAGES } from '@/lib/images';
import { authService } from '@/services/auth.service';

/**
 * Retire an ARTINU-issued password (requirements §1).
 *
 * A space owner is sent here by `ProtectedRoute` on their first sign-in,
 * because the password they hold is one we generated and therefore one we have
 * seen. Anyone else can reach it deliberately to change their own password.
 *
 * The current password is asked for even though the visitor is already signed
 * in: a session left open on a café counter should not be enough to take the
 * account over.
 */
const schema = z
  .object({
    currentPassword: z.string().min(1, 'Enter the password ARTINU gave you'),
    password: passwordSchema,
    confirmPassword: z.string().min(1, 'Confirm your new password'),
  })
  .refine((values) => values.password === values.confirmPassword, {
    message: 'Both passwords must match',
    path: ['confirmPassword'],
  });

type Values = z.infer<typeof schema>;

export default function ChangePasswordPage() {
  const navigate = useNavigate();
  const { user, setSession, homePath } = useAuth();
  const forced = user?.mustChangePassword === true;

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: { currentPassword: '', password: '', confirmPassword: '' },
  });

  const change = useMutation({
    mutationFn: (values: Values) =>
      authService.changePassword({
        currentPassword: values.currentPassword,
        password: values.password,
      }),
    onSuccess: (session) => {
      // The refreshed session carries mustChangePassword: false, which is what
      // releases the guard — without it the redirect below bounces straight back.
      setSession(session);
      toast.success('Password updated. This one is yours alone.');
      navigate(homePath, { replace: true });
    },
    onError: (error) => toast.error(errorMessage(error)),
  });

  return (
    <AuthSplit image={IMAGES.cafeInterior} imageAlt="A framed photograph on a warm café wall">
      <div className="mx-auto w-full max-w-md">
        <h1 className="font-display text-[2rem] leading-tight text-ink sm:text-[2.5rem]">
          {forced ? 'Choose your own password.' : 'Change your password.'}
        </h1>
        <p className="prose-quiet mt-4">
          {forced
            ? 'The password you signed in with was generated by ARTINU, so it is not private to you. Replace it now and it never gets used again.'
            : 'Pick something only you know. You will stay signed in on this device.'}
        </p>
      </div>

      <form
        onSubmit={handleSubmit((values) => change.mutate(values))}
        className="mx-auto mt-8 w-full max-w-md"
      >
        <AuthCard
          title="New password"
          description={forced ? 'One step, then you are in.' : undefined}
        >
          <div className="space-y-4">
            <Field
              label={forced ? 'The password ARTINU gave you' : 'Current password'}
              htmlFor="currentPassword"
              error={errors.currentPassword?.message}
            >
              <PasswordInput
                id="currentPassword"
                autoComplete="current-password"
                placeholder={forced ? 'e.g. KRPD-4827' : 'Your current password'}
                invalid={!!errors.currentPassword}
                {...register('currentPassword')}
              />
            </Field>

            <Field label="New password" htmlFor="password" error={errors.password?.message}>
              <PasswordInput
                id="password"
                autoComplete="new-password"
                placeholder="Create a password"
                invalid={!!errors.password}
                {...register('password')}
              />
              <PasswordRules password={watch('password')} />
            </Field>

            <Field
              label="Confirm new password"
              htmlFor="confirmPassword"
              error={errors.confirmPassword?.message}
            >
              <PasswordInput
                id="confirmPassword"
                autoComplete="new-password"
                placeholder="Type it again"
                invalid={!!errors.confirmPassword}
                {...register('confirmPassword')}
              />
            </Field>

            <Button type="submit" className="w-full" loading={change.isPending}>
              <KeyRound className="size-4" /> Save new password
            </Button>
          </div>
        </AuthCard>
      </form>
    </AuthSplit>
  );
}
